import type { NewsCategory, NewsSourceConfig } from "@/types/news";

/** Revalidate news aggregates ~1 hour for fresher coverage. */
export const NEWS_REVALIDATE_SECONDS = 3600;
export const NEWS_FETCH_TIMEOUT_MS = 10000;

export const NEWS_USER_AGENT =
  "Mozilla/5.0 (compatible; BoatingChicago/1.0; +https://boatingchicago.com; news aggregation)";

/**
 * Allowlisted RSS / Atom / official feed sources only.
 * Items from filtered feeds must match includeKeywords when set.
 */
export const NEWS_SOURCES: NewsSourceConfig[] = [
  {
    id: "great-lakes-now",
    name: "Great Lakes Now",
    domain: "greatlakesnow.org",
    feedUrl: "https://www.greatlakesnow.org/feed/",
    defaultCategory: "Great Lakes",
    includeKeywords: [
      "michigan",
      "chicago",
      "illinois",
      "indiana",
      "wisconsin",
      "boat",
      "harbor",
      "marina",
      "fishing",
      "coast guard",
      "ship",
      "vessel",
      "lake michigan",
      "recreation",
      "tourism",
      "water quality",
      "beach",
      "milwaukee",
      "kenosha",
      "racine",
      "new buffalo",
      "great lakes",
      "water level",
      "seiche",
      "shipping",
    ],
    excludeKeywords: [
      "apostle islands",
      "lake superior",
      "lake erie",
      "lake ontario",
      "toronto",
      "buffalo ny",
    ],
    enabled: true,
  },
  {
    id: "illinois-sea-grant",
    name: "Illinois-Indiana Sea Grant",
    domain: "iiseagrant.org",
    feedUrl: "https://iiseagrant.org/feed/",
    defaultCategory: "Great Lakes",
    includeKeywords: [
      "lake michigan",
      "great lakes",
      "boat",
      "harbor",
      "marina",
      "fishing",
      "beach",
      "water quality",
      "chicago",
      "invasive",
      "aquaculture",
      "flood",
      "shoreline",
      "coastal",
      "kayak",
      "sail",
      "vessel",
      "shipping",
      "hypoxia",
      "algae",
      "e. coli",
      "swim",
    ],
    enabled: true,
  },
  {
    id: "wisconsin-sea-grant",
    name: "Wisconsin Sea Grant",
    domain: "seagrant.wisc.edu",
    feedUrl: "https://www.seagrant.wisc.edu/feed/",
    defaultCategory: "Wisconsin",
    includeKeywords: [
      "lake michigan",
      "great lakes",
      "boat",
      "harbor",
      "marina",
      "fishing",
      "beach",
      "milwaukee",
      "kenosha",
      "racine",
      "sheboygan",
      "sturgeon",
      "aquaculture",
      "water quality",
      "lighthouse",
      "coastal",
      "nearshore",
      "shipping",
    ],
    excludeKeywords: ["lake superior"],
    enabled: true,
  },
  {
    id: "chicago-park-district",
    name: "Chicago Park District",
    domain: "chicagoparkdistrict.com",
    feedUrl: "https://www.chicagoparkdistrict.com/rss.xml",
    defaultCategory: "Events",
    includeKeywords: [
      "harbor",
      "marina",
      "boat",
      "beach",
      "lake michigan",
      "lakefront",
      "swim",
      "31st",
      "diversey",
      "montrose",
      "belmont",
      "burnham",
      "jackson",
      "du sable",
      "northerly island",
      "air and water",
      "wild mile",
      "riverwalk",
      "chicago river",
      "water",
      "kayak",
      "rowing",
      "sailing",
    ],
    enabled: true,
  },
  {
    id: "nws-lot-news",
    name: "NWS Chicago (LOT)",
    domain: "weather.gov",
    feedUrl: "https://www.weather.gov/rss_page.php?site_name=lot",
    defaultCategory: "Safety",
    /** Prefer marine/climate/local headlines; empty include = accept all parsed items. */
    enabled: true,
  },
  {
    id: "nws-mkx-news",
    name: "NWS Milwaukee (MKX)",
    domain: "weather.gov",
    feedUrl: "https://www.weather.gov/rss_page.php?site_name=mkx",
    defaultCategory: "Wisconsin",
    includeKeywords: [
      "lake michigan",
      "marine",
      "small craft",
      "gale",
      "beach",
      "rip current",
      "milwaukee",
      "kenosha",
      "racine",
      "sheboygan",
      "climate",
      "summer",
      "winter",
      "nearshore",
    ],
    enabled: true,
  },
  {
    id: "nws-cap-il",
    name: "NWS Alerts (Illinois)",
    domain: "weather.gov",
    feedUrl: "https://api.weather.gov/alerts/active.atom?area=IL",
    defaultCategory: "Safety",
    includeKeywords: [
      "nws chicago",
      "lake michigan",
      "marine",
      "small craft",
      "gale",
      "beach",
      "rip current",
      "special marine",
      "nearshore",
    ],
    enabled: true,
  },
  {
    id: "nws-cap-wi",
    name: "NWS Alerts (Wisconsin)",
    domain: "weather.gov",
    feedUrl: "https://api.weather.gov/alerts/active.atom?area=WI",
    defaultCategory: "Wisconsin",
    includeKeywords: [
      "lake michigan",
      "marine",
      "small craft",
      "gale",
      "beach",
      "rip current",
      "milwaukee",
      "kenosha",
      "racine",
      "sheboygan",
      "special marine",
      "nws milwaukee",
    ],
    enabled: true,
  },
  {
    id: "nws-cap-in",
    name: "NWS Alerts (Indiana)",
    domain: "weather.gov",
    feedUrl: "https://api.weather.gov/alerts/active.atom?area=IN",
    defaultCategory: "Indiana",
    includeKeywords: [
      "lake michigan",
      "marine",
      "small craft",
      "gale",
      "beach",
      "rip current",
      "michigan city",
      "new buffalo",
      "porter",
      "laporte",
      "special marine",
      "nws northern indiana",
      "nws chicago",
    ],
    enabled: true,
  },
  {
    id: "block-club-chicago",
    name: "Block Club Chicago",
    domain: "blockclubchicago.org",
    feedUrl: "https://blockclubchicago.org/feed/",
    defaultCategory: "Chicago Boating",
    includeKeywords: [
      "harbor",
      "marina",
      "boat",
      "lake michigan",
      "navy pier",
      "riverwalk",
      "chicago river",
      "beach",
      "lakefront",
      "kayak",
      "jet ski",
      "sail",
      "coast guard",
      "drowning",
      "rescue",
      "water rescue",
      "swim advisory",
      "montrose",
      "ohio street beach",
      "north avenue beach",
      "31st street beach",
      "playpen",
    ],
    enabled: true,
  },
];

export const NEWS_CATEGORY_RELATED: Record<
  NewsCategory,
  { href: string; label: string }[]
> = {
  "Chicago Boating": [
    { href: "/destinations/chicago", label: "Boating in Chicago" },
    { href: "/weather", label: "Boating Weather" },
  ],
  "Lake Michigan": [
    { href: "/weather", label: "Lake Conditions" },
    { href: "/lakes/lake-michigan-chicago", label: "Lake Michigan Guide" },
  ],
  Safety: [
    { href: "/weather", label: "Boating Weather & Alerts" },
    { href: "/guides", label: "Boating Guides" },
  ],
  Events: [
    { href: "/events", label: "Boating Events" },
    { href: "/navy-pier-fireworks-boat-rentals", label: "Fireworks Boats" },
  ],
  Fishing: [
    { href: "/fishing-charters-chicago", label: "Fishing Charters" },
  ],
  "Harbors & Marinas": [
    { href: "/marinas", label: "Marinas Directory" },
    { href: "/boat-launches", label: "Boat Launches" },
  ],
  Wisconsin: [
    { href: "/destinations", label: "Destinations" },
    { href: "/weather?location=lake-geneva", label: "Lake Geneva Weather" },
  ],
  Indiana: [
    { href: "/destinations", label: "Destinations" },
    { href: "/weather", label: "Lake Conditions" },
  ],
  "Great Lakes": [
    { href: "/lake-michigan-boating-guide", label: "Lake Michigan Guide" },
    { href: "/weather", label: "Boating Weather" },
  ],
};

/** Seasonal tip pool for Chicago Boating Brief (static, factual, conservative). */
export const SEASONAL_BOATING_TIPS = [
  "Lake Michigan water stays colder than downtown air for much of the season — dress for the water temperature, not the skyline temperature.",
  "Afternoon lake breezes can differ sharply from Loop conditions. Check the nearshore marine forecast before you leave the harbor.",
  "Thunderstorms can build quickly over the lake. If you hear thunder, get off the water and seek a safe harbor.",
  "Small craft advisories are common on windy days. Recreational boaters should treat them as a strong signal to reconsider departure.",
  "Night fireworks and special-event weekends fill harbors early — plan fuel, dockage, and a sober captain before you go.",
];
